import profile from '@/assets/image/profile.jpg';

export const DUMMY_APPLICATION_DATA = [
  {
    id: 1,
    status: '서류 합격' as const,
    profileImage: profile,
    name: '김철수',
    part: '웹' as const,
    isDoNotRead: false,
    doNotReadBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    evaluationStatus: true,
    evaluatedBy: {
      기획: true,
      디자인: true,
      서버: true,
      iOS: false,
      안드로이드: false,
      웹: true,
      회장: true,
    },
    submissionTime: '2024-01-15 14:30:00',
    recentGeneration: 33,
    birth: '2000-03-15',
    university: '서울대학교',
    major: '컴퓨터공학과',
    email: 'soptsoptsoptsoptsopt@sopt.org',
    phone: '010-1234-5678',
  },
  {
    id: 2,
    status: '불합격' as const,
    profileImage: profile,
    name: '이영희',
    part: '디자인' as const,
    isDoNotRead: true,
    doNotReadBy: {
      기획: true,
      디자인: true,
      서버: true,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: true,
    },
    evaluationStatus: false,
    evaluatedBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    submissionTime: '2024-01-16 09:15:00',
    recentGeneration: 32,
    birth: '1999-07-22',
    university: '연세대학교',
    major: '시각디자인학과',
    email: 'lee.younghee@example.com',
    phone: '010-2345-6789',
  },
  {
    id: 3,
    status: '확인 전' as const,
    profileImage: profile,
    name: '박민수',
    part: '서버' as const,
    isDoNotRead: false,
    doNotReadBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    evaluationStatus: false,
    evaluatedBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    submissionTime: '2024-01-17 16:45:00',
    recentGeneration: 34,
    birth: '2001-11-08',
    university: '고려대학교',
    major: '정보보안학과',
    email: 'park.minsu@example.com',
    phone: '010-3456-7890',
  },
  {
    id: 4,
    status: '최종 합격' as const,
    profileImage: profile,
    name: '정수진',
    part: 'iOS' as const,
    isDoNotRead: false,
    doNotReadBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    evaluationStatus: true,
    evaluatedBy: {
      기획: true,
      디자인: true,
      서버: true,
      iOS: true,
      안드로이드: true,
      웹: true,
      회장: true,
    },
    submissionTime: '2024-01-18 11:20:00',
    recentGeneration: 33,
    birth: '2000-05-12',
    university: '한양대학교',
    major: '컴퓨터소프트웨어학과',
    email: 'jung.sujin@example.com',
    phone: '010-4567-8901',
  },
  {
    id: 5,
    status: '서류 합격' as const,
    profileImage: profile,
    name: '최동현',
    part: '안드로이드' as const,
    isDoNotRead: false,
    doNotReadBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    evaluationStatus: true,
    evaluatedBy: {
      기획: true,
      디자인: false,
      서버: true,
      iOS: false,
      안드로이드: true,
      웹: false,
      회장: true,
    },
    submissionTime: '2024-01-19 13:10:00',
    recentGeneration: 31,
    birth: '1998-12-03',
    university: '성균관대학교',
    major: '전자전기공학부',
    email: 'choi.donghyun@example.com',
    phone: '010-5678-9012',
  },
  {
    id: 6,
    status: '불합격' as const,
    profileImage: profile,
    name: '강지원',
    part: '기획' as const,
    isDoNotRead: true,
    doNotReadBy: {
      기획: true,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    evaluationStatus: false,
    evaluatedBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    submissionTime: '2024-01-20 10:30:00',
    recentGeneration: 33,
    birth: '2000-08-25',
    university: '중앙대학교',
    major: '경영학과',
    email: 'kang.jiwon@example.com',
    phone: '010-6789-0123',
  },
  {
    id: 7,
    status: '확인 전' as const,
    profileImage: profile,
    name: '윤서연',
    part: '웹' as const,
    isDoNotRead: false,
    doNotReadBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    evaluationStatus: false,
    evaluatedBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    submissionTime: '2024-01-21 15:45:00',
    recentGeneration: 34,
    birth: '2001-02-14',
    university: '경희대학교',
    major: '컴퓨터공학과',
    email: 'yoon.seoyeon@example.com',
    phone: '010-7890-1234',
  },
  {
    id: 8,
    status: '서류 합격' as const,
    profileImage: profile,
    name: '임태호',
    part: '서버' as const,
    isDoNotRead: false,
    doNotReadBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    evaluationStatus: true,
    evaluatedBy: {
      기획: true,
      디자인: false,
      서버: true,
      iOS: false,
      안드로이드: false,
      웹: true,
      회장: false,
    },
    submissionTime: '2024-01-22 08:20:00',
    recentGeneration: 32,
    birth: '1999-09-30',
    university: '부산대학교',
    major: '정보컴퓨터공학과',
    email: 'lim.taeho@example.com',
    phone: '010-8901-2345',
  },
  {
    id: 9,
    status: '최종 합격' as const,
    profileImage: profile,
    name: '한미영',
    part: '디자인' as const,
    isDoNotRead: false,
    doNotReadBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    evaluationStatus: true,
    evaluatedBy: {
      기획: true,
      디자인: true,
      서버: true,
      iOS: false,
      안드로이드: false,
      웹: true,
      회장: true,
    },
    submissionTime: '2024-01-23 12:15:00',
    recentGeneration: 33,
    birth: '2000-06-18',
    university: '홍익대학교',
    major: '산업디자인학과',
    email: 'han.miyeong@example.com',
    phone: '010-9012-3456',
  },
  {
    id: 10,
    status: '불합격' as const,
    profileImage: profile,
    name: '송재현',
    part: 'iOS' as const,
    isDoNotRead: true,
    doNotReadBy: {
      기획: false,
      디자인: true,
      서버: true,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: true,
    },
    evaluationStatus: false,
    evaluatedBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    submissionTime: '2024-01-24 17:30:00',
    recentGeneration: 31,
    birth: '1998-04-07',
    university: '전남대학교',
    major: '컴퓨터공학과',
    email: 'song.jaehyun@example.com',
    phone: '010-0123-4567',
  },
  {
    id: 11,
    status: '확인 전' as const,
    profileImage: profile,
    name: '조은영',
    part: '안드로이드' as const,
    isDoNotRead: false,
    doNotReadBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    evaluationStatus: false,
    evaluatedBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    submissionTime: '2024-01-25 14:05:00',
    recentGeneration: 34,
    birth: '2001-10-11',
    university: '전북대학교',
    major: '전자정보공학부',
    email: 'jo.eunyoung@example.com',
    phone: '010-1234-5678',
  },
  {
    id: 12,
    status: '서류 합격' as const,
    profileImage: profile,
    name: '오승준',
    part: '기획' as const,
    isDoNotRead: false,
    doNotReadBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    evaluationStatus: true,
    evaluatedBy: {
      기획: true,
      디자인: true,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: true,
    },
    submissionTime: '2024-01-26 09:50:00',
    recentGeneration: 33,
    birth: '2000-01-29',
    university: '충남대학교',
    major: '경영정보학과',
    email: 'oh.seungjun@example.com',
    phone: '010-2345-6789',
  },
  {
    id: 13,
    status: '최종 합격' as const,
    profileImage: profile,
    name: '배수진',
    part: '웹' as const,
    isDoNotRead: false,
    doNotReadBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    evaluationStatus: true,
    evaluatedBy: {
      기획: true,
      디자인: true,
      서버: true,
      iOS: false,
      안드로이드: false,
      웹: true,
      회장: true,
    },
    submissionTime: '2024-01-27 11:40:00',
    recentGeneration: 32,
    birth: '1999-12-05',
    university: '충북대학교',
    major: '컴퓨터공학과',
    email: 'bae.sujin@example.com',
    phone: '010-3456-7890',
  },
  {
    id: 14,
    status: '불합격' as const,
    profileImage: profile,
    name: '남기준',
    part: '서버' as const,
    isDoNotRead: true,
    doNotReadBy: {
      기획: true,
      디자인: false,
      서버: true,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    evaluationStatus: false,
    evaluatedBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    submissionTime: '2024-01-28 16:25:00',
    recentGeneration: 31,
    birth: '1998-07-16',
    university: '강원대학교',
    major: '정보통신공학과',
    email: 'nam.kijun@example.com',
    phone: '010-4567-8901',
  },
  {
    id: 15,
    status: '확인 전' as const,
    profileImage: profile,
    name: '유하나',
    part: '디자인' as const,
    isDoNotRead: false,
    doNotReadBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    evaluationStatus: false,
    evaluatedBy: {
      기획: false,
      디자인: false,
      서버: false,
      iOS: false,
      안드로이드: false,
      웹: false,
      회장: false,
    },
    submissionTime: '2024-01-29 13:55:00',
    recentGeneration: 34,
    birth: '2001-03-21',
    university: '제주대학교',
    major: '디자인학과',
    email: 'yoo.hana@example.com',
    phone: '010-5678-9012',
  },
];
